### ISSUE TITLE
add support to switch URL / set variable

### ISSUE THREAD

**Issue by pascaldufour** [icemobilelab/minosse#19]
For testing different environments I like to switch between the target URL for environment 1 and environment 2. Currently I have the default value Localhost and if I specify I need to enter the complete URL. 

An improvement would be to add the possibility to set a variable like environment. 
An example you see below. 
I set variable <variableName> to  <type> <value>

I set variable targetUrl to string http://test.icemobile.com
I send a GET request to {targetUrl}/programs/{programId}

This variable should be available in the feature file.

**Comment by NinjaTux** [comment]
Hmm basically what's requested is the implementation of a templating system for strings.
Makes sense to me and I like it. Let's push this.

**Comment by jwoudenberg** [comment]
I like it too! That's why it's already part of the library :).

Instead of `variable` use `property` and you should be ready to go!

**Comment by jwoudenberg** [comment]
I'm reopening this, because I see that the documentation is missing this feature.

**Comment by jwoudenberg** [comment]
Ok, templating of url's is documented now!
