### ISSUE TITLE
There is not an easy way of chaining requests

### ISSUE THREAD

**Issue by dgonzalez** [icemobilelab/minosse#48]
If I want to test a flow that has two requests and the data of the second request depends on the data coming back from the first request there is no documentation on how to access to the response object more than the response code.

**Comment by pixeleet** [comment]
https://github.com/icemobilelab/minosse/wiki/Steps#save-the-response-body

Some pseudo code:
```
Scenario: Account activation
        And I set property request body to testdata account.good
        When I send a POST request to /account
        Then the response status code is 201
        And I set property activationKey to property activationKey of response body
        # Activate
        When I send a GET request to /v1/account/activate/{activationKey}
        Then the response status code is 200
```

**Comment by dgonzalez** [comment]
Oh nice, cheers!
